#+TITLE: New Blog, New Start

#+BEGIN_QUOTE
书写是为了更好的思考。

— 刘未鹏
#+END_QUOTE

刚上大学的时候，我给高中同桌发短信咨询 QQ 该怎么用，他回了一条“计算机的教育要从娃娃抓起”……那时候我刚刚学会如何从控制面板里面卸载软件，刚刚学会收发 Email，写 blog 对我来说是一件相当时髦的事情啊。

最开始用的是线上服务，什么 Dreamhost/DNS/WordPress 对于当时的我来说是难以逾越的技术难题。大概有一年多的时间，我在百度空间，和讯博客，博客园， [[http://en.wikipedia.org/wiki/Windows_Live_Spaces][Windows Live Spaces]] 等各种 blog 平台上写（ +转载+ ）文章，玩（ +自嗨+ ）得不亦乐乎。后来咱不是会写点小程序了嘛，就希望能找个支持代码高亮，并且广告要少些的博客平台。无意间找到了 [[http://www.is-programmer.com/][is-programmer]] ，试用了下，很不错，就在那里安了家，迄已五年。

[[http://cnlox.is-programmer.com/][行者无疆 始于足下]]，这个 blog 基本上忠实地记录了我个人学习计算机的历程。最开始是学习 Linux/LaTeX，后来忙于学业 （OpenGL/Assembly），再后来开始实习（终于学会了 SSH/SCP/Shell Script，掩面），疲于奔命，总算天幸顺利毕业，进入百度，后来偷得浮生，后来一夜之间……五年时间，不长不短，对于 [[http://blog.watashi.ws/][天才选手]] ，五年可以从无到有，站到世界之颠。对于我辈俗人，五年时间，也许刚刚够敲开计算机世界的大门吧。 五年来如果说有什么成就，就是始终没有离开 Open Source。这种坚持终于让我在去年收获了 200+ 个 github star，也让我进了 OpenStack 的贡献者名单。想想自己写的代码能够跑在别人的机器上，make the world a better place，还是很开心的。是谁说过，«[[http://book.douban.com/subject/4006425/][我是一只 IT 小小鸟]]»。

#+BEGIN_QUOTE
认真的写作有如雕刻。
#+END_QUOTE

工作以后，blog 更新的频率大幅下降， 每篇 blog 的长度却大幅提高，随之而来的就是每篇 blog 写作时间的水涨船高。一方面美其名曰“工作忙（ +其实是懒+ ）”，另一方面，自己偶尔回翻下自己以前的文章，个中观点语句，常感羞愧难当。因此每次写作，总是有些诚惶诚恐，咬文嚼字，条分缕析，大耗体力，唯恐贻笑大方。

写作有如登山，一日风睛，柳暗花明，辛苦求索的背后，是对自己生活的反思和锤炼。我常常在认真的写作中发现自己的思想盲点，正如行者登山，辛苦自不必说，孤独也是常态，只是这辛苦孤独之外，常常会伴随着山重水复般的壮丽风景。

大概在一年前，我开始着手寻找新的 blog 平台， [[http://www.is-programmer.com/][is-programmer]] 对新手程序员而言是相当好的 blog 的平台，但是已经越来越无法满足我的需求，因此我将我的注意力转到了所谓的 static blog/site generator 上。这个折腾的过程一波三折，高潮不断，快感连连，折腾的结果就是你现在看到的新的 [[http://xiaohanyu.me][行者无疆 始于足下]] 。其中的技术细节繁复冗长，我会再写一篇文章加以详述。

行走，思考，在路上。New blog, new start。“身体与心灵，总要有一个在路上”，自勉。
